TJIPMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from TJIPMS import views

urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name='index'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^account/', include('account.urls')),
	url(r'^tjadmin/', include('tjadmin.urls')),
	url(r'^project/', include('project.urls')),
	url(r'^announcement/', include('announcement.urls')),
	url(r'^i18n', views.language_switch, name="language_switch"),
	url(r'^delete_post/$', views.delete_post, name="delete_post"),
	url(r'^update_post/$', views.update_post, name="update_post"),
)

announcement/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Announcement(models.Model):
    title = models.CharField(max_length=64, verbose_name=_("Title"))
    time = models.DateTimeField(auto_now_add=True)
    url = models.URLField(verbose_name=_("URL"))

    def __unicode__(self):
        return self.title

project/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _



class Project(models.Model):
    DEPARTMENT = "A"
    UNIVERSITY = "B"
    PROVINCE = "C"
    NATION = "D"
    TYPE_CHOICES = (
        (DEPARTMENT, _('A. Department')),
        (UNIVERSITY, _('B. University')),
        (PROVINCE, _('C. Province')),
        (NATION, _('D. Nation')),
    )

    STATUS_CHOICES = (
        ("PENDING", _('A. PENDING')),
        ("APPROVED", _('B. APPROVED')),
        ("REJECTED", _('C. REJECTED')),
    )  

    title = models.CharField(max_length=50)
    leader = models.ForeignKey("account.Student", related_name="leading_project")
    description = models.TextField()
    members = models.ManyToManyField('account.Student', related_name="involved_project", db_constraint=False)
    teacher = models.ForeignKey('account.Teacher')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    #TODO do we need approved_time & finished_time
    approved_time = models.DateTimeField(null=True)
    finished_time = models.DateTimeField(null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="PENDING")

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('project_detail', args=[str(self.id)])


class Mark(models.Model):
    project = models.ForeignKey('project.Project')
    comment = models.TextField()
    credit = models.IntegerField()
    # TODO
    # stage

project/forms.py
from django import forms
from project.models import Project
from django.utils.translation import ugettext_lazy as _


class ProposalForm(forms.Form):
    title = forms.CharField(label=_("Title"), max_length=50,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    leader = forms.IntegerField(label=_("Leader"),
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': _('Student ID'), 'readonly':True}))
    member1 = forms.IntegerField(label=_("Member"), required=False,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _('Student ID')}))
    member2 = forms.IntegerField(label=_("Member"), required=False,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': _('Student ID')}))
    type = forms.ChoiceField(label=_("Type"), choices=Project.TYPE_CHOICES,
                             widget=forms.Select(attrs={'class': 'form-control'}, choices=Project.TYPE_CHOICES))
    instructor = forms.CharField(label=_("Instructor"), max_length=5,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(label=_("Description"),
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '4'}))

announcement/views.py
from django.views.generic import ListView
from TJIPMS.views import LoginRequiredMixin
from announcement.models import Announcement


class AnnouncementListView(LoginRequiredMixin, ListView):
    template_name = ""
    model = Announcement

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="http://getbootstrap.com/favicon.ico">
        <title>Tongji Innovation Management System - Student Portal</title>
        <!-- Bootstrap core CSS -->
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/material/css/roboto.min.css" rel="stylesheet">
        <link href="/static/material/css/material.min.css" rel="stylesheet">
        <link href="/static/material/css/ripples.min.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="/static/base.css" rel="stylesheet">
        <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                    <a class="navbar-brand" href="{% url 'index' %}">{% trans "Tongji Innovation Management System"%}</a>
                </div>
                <div class="navbar-collapse collapse navbar-inverse-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        {% if not user.is_superuser %}
                        <li><a href="{% url "create_proposal" %}">{% trans "Proposal" %}</a></li>
                        {% endif %}
                        <li><a href="{% url "announcement_list" %}">{% trans "Announcement" %}</a></li>
                        {% if user.is_superuser %}
                        <li><a href="{% url "search_list" %}">{% trans "Search" %}</a></li>
                        <li><a href="{% url "project_list" %}">{% trans "Project" %}</a></li>
                        <li><a href="{% url "project_stats" %}">{% trans "Statistics" %}</a></li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">{{user.first_name }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% if not user.is_superuser %}
                                <li><a href="{% url "profile" %}">{% trans "Profile" %}</a></li>
                                {% endif %}
                                <li><a href="{% url "setting" %}">{% trans "Account Settings" %}</a></li>
                                {% if user.is_superuser %}
                                <li><a href="{% url "superuser" %}">{% trans "Super User" %}</a></li>
                                {% endif %}
                                <li class="divider"></li>
                                <li><a href="{% url "logout" %}">{% trans "Log Out" %}</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if LANGUAGE_CODE == 'en' %}
                        <li><a href="{% url "language_switch" %}?code=zh-cn&next={{ request.get_full_path }}">中文</a></li>
                        {% endif %}
                        {% if LANGUAGE_CODE == 'zh-cn' %}
                        <li><a href="{% url "language_switch" %}?code=en&next={{ request.get_full_path }}">English</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block page %}
        {% endblock page %}
    </body>

    <script src="/static/bootstrap/js/jquery.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/bootstrap/js/ie10-viewport-bug-workaround.js"></script>
    <script src="/static/bootstrap/js/ie-emulation-modes-warning.js"></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block page %}
{% if user.is_superuser %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 center-block">
        <div class="well bs-component">
            <legend>Hello {% trans "Super User" %}</legend>
                <h5>Here are the three super powers</h5>
                <a class="btn btn-primary btn-raised" href="{% url "tjadmin_create_student" %}">{% trans "Create Student" %}</a>
                <a class="btn btn-primary btn-raised" href="{% url "tjadmin_upload_student" %}">{% trans "Upload Student List" %}</a>
                <a class="btn btn-primary btn-raised" href="{% url "tjadmin_create_announcement" %}">{% trans "Create Announcement" %}</a>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <div class="well bs-component">
                <legend>{% trans "Leading Project" %}</legend>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for lp in leading_project%}
                    <div class="panel panel-default" id="post-{{lp.id}}">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <div class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#lp{{ forloop.counter }}" aria-expanded="false" aria-controls="lp{{ forloop.counter }}">
                                    {{ lp }}
                                    <div class="icon-preview pull-right">
                                        {% if lp.status == "PENDING" %}
                                            {# <p class="text-muted">{% trans "Status" %}</p> #}
                                            <p class="text-muted">{% trans "PENDING" %}</p>
                                        {% elif lp.status == "APPROVED" %}
                                            <p class="text-success">{% trans "APPROVED" %}</p>
                                        {% else%}
                                            <p class="text-danger">{% trans "REJECTED" %}</p>
                                        {% endif%}
                                    </div>
                                </div>
                            </h4>
                        </div>
                        <div id="lp{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <form class="form-inline">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <form action="." method="post" class="form-horizontal">
                                                {% csrf_token %}
                                                <fieldset>
                                                    <div class="form-group">
                                                        <label for="id_leader" class="col-md-4 control-label">Leader</label>
                                                        <div class="col-md-8">
                                                            {{ lp.leader }}
                                                            {# <input class="form-control" id="leader-{{ lp.id }}" value="{{ lp.leader }}"> #}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Teacher</label>
                                                        <div class="col-md-8">
                                                            {{ lp.teacher }}
                                                            {# <input class="form-control" id="teacher-{{ lp.id }}" value="{{ lp.teacher }}"> #}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Type</label>
                                                        <div class="col-md-8">
                                                            {{ lp.get_type_display }}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Description</label>
                                                        <div class="col-md-8">
                                                            {{ lp.description }}
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="col-md-2">
                                                            <button id="delete-{{ lp.id }}" class="btn btn-danger">{% trans "Delete" %}</button>
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </form>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="well bs-component">
                <legend>{% trans "Involved Project" %}</legend>
                <div class="panel-group" id="accordion1" role="tablist" aria-multiselectable="true">
                    {% for ip in involved_project%}
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <div class="collapsed" data-toggle="collapse" data-parent="#accordion1" href="#ip{{ forloop.counter }}" aria-expanded="false" aria-controls="ip{{ forloop.counter }}">
                                    {{ ip }}
                                    <div class="icon-preview pull-right">
                                        {% if ip.status == "PENDING" %}
                                            {# <p class="text-muted">{% trans "Status" %}</p> #}
                                            <p class="text-muted">{% trans "PENDING" %}</p>
                                        {% elif ip.status == "APPROVED" %}
                                            <p class="text-success">{% trans "APPROVED" %}</p>
                                        {% else%}
                                            <p class="text-danger">{% trans "REJECTED" %}</p>
                                        {% endif%}
                                    </div>
                                </div>
                            </h4>
                        </div>
                        <div id="ip{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <form class="form-inline">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <form action="." method="post" class="form-horizontal">
                                                {% csrf_token %}
                                                <fieldset>
                                                    <div class="form-group">
                                                        <label for="id_leader" class="col-md-4 control-label">Leader</label>
                                                        <div class="col-md-8">
                                                            {{ ip.leader }}
                                                            {# <input class="form-control" id="leader-{{ ip.id }}" value="{{ ip.leader }}"> #}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Teacher</label>
                                                        <div class="col-md-8">
                                                            {{ ip.teacher }}
                                                            {# <input class="form-control" id="teacher-{{ ip.id }}" value="{{ ip.teacher }}"> #}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Type</label>
                                                        <div class="col-md-8">
                                                            {{ ip.get_type_display }}
                                                            {# <input class="form-control" id="type-{{ ip.id }}" value="{{ ip.get_type_display }}"> #}
                                                        </div>
                                                        <label for="id_leader" class="col-md-4 control-label">Description</label>
                                                        <div class="col-md-8">
                                                            {{ ip.description }}
                                                            {# <textarea class="form-control" rows="3" id="description-{{ ip.id }}">{{ ip.description }}</textarea> #}
                                                        </div>
                                                    </div>
                                                </fieldset>
                                            </form>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<script src="/static/js/main.js"></script>
{% endblock %}